name: Build and Deploy Laravel via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Tailwind/Vite assets
        run: |
          npm install
          npm run build

      - name: Prepare public folder
        run: |
          rm -rf public/build-upload
          mkdir public/build-upload
          cp -r public/* public/build-upload/

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.6.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/build-upload/
          server-dir: /
          git-ftp-args: --delete