name: Build JS Assets & Laravel Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing_db
      DB_USERNAME: root
      DB_PASSWORD: ''
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: testing_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql, curl

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts

      - name: Copy .env.testing
        run: cp .env.testing .env

      - name: Run migrations
        run: php artisan migrate --env=testing --force

      - name: Run Laravel tests
        run: php artisan test --env=testing

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build JS assets
        run: |
          npm install
          npm run build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/build/
          server-dir: build/
          git-ftp-args: --delete