name: Build Laravel and Deploy Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies & build assets
        run: |
          npm ci
          npm run build

      - name: Move public files to root
        run: |
          cp -r public/* ./
          rm -rf public

      - name: Clean up unnecessary files
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -rf .github
          rm -rf package*.json vite.config.* tailwind.config.* postcss.config.*

      - name: Push built files to deploy branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: .
