name: Build Laravel and Deploy Branch

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies & build assets
        run: |
          npm install
          npm run build

      - name: Move public files to root
        run: |
          cp -r public/* ./

      - name: Clean up unnecessary files
        run: |
          rm -rf node_modules
          rm -rf tests
          rm -rf .github
          rm -rf package*.json vite.config.* tailwind.config.* postcss.config.*

      - name: Push built files to master branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(ci): auto build and deploy Laravel assets [skip ci]" || echo "No changes to commit"
          git push origin master
